blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    
   path('', views.PostListView.as_view(), name='post_list'),
   path('tag/<slug:tag_slug>/', views.PostListView.as_view(), name='post_list_by_tag'),
   path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
   path('<int:post_id>/share/', views.post_share, name='post_share'),
   path('search/', views.post_search, name='post_search'),



]

mysite/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone 
from django.contrib.auth.models import User 
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
		def get_queryset(self):
			return super(PublishedManager,self).get_queryset().filter(status='published')

class Post(models.Model):
	STATUS_CHOICES = (
			('draft', 'Draft'),
			('published', 'Published'),
	)
	title   = models.CharField(max_length=250)
	slug    = models.SlugField(max_length=250 , unique_for_date='publish')
	author  = models.ForeignKey(User,on_delete=models.CASCADE, related_name='blog_posts')
	body    = models.TextField()
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	update  = models.DateTimeField(auto_now=True)
	status  = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

	class Meta:
		ordering = ('-publish',)

	def __str__(self):
		return self.title

	
	objects = models.Manager()
	published = PublishedManager()
	tags = TaggableManager()
	
	def get_absolute_url(self):
		return reverse('blog:post_detail', args=[ self.publish.year, self.publish.strftime('%m'), self.publish.strftime('%d'), self.slug ])

class Comment(models.Model):
	post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('created',)

	def __str__(self):
		return 'Komentarz dodany przez {} dla posta {}'.format(self.name,self.post)

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
	name = forms.CharField(max_length=25)
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False,widget=forms.Textarea)


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render , get_object_or_404
from .models import Post, Comment
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from .forms import EmailPostForm , CommentForm , SearchForm
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector

class PostListView(ListView):
	
	context_object_name = 'posts'
	paginate_by = 3
	template_name = 'blog/post/list.html'
	allow_empty = False
	tag = None
	
	def get_queryset(self):
		try:
			tag_slug = self.kwargs['tag_slug']
			if ( tag_slug ):
				#tag_slug = self.kwargs['tag_slug']
				tag = get_object_or_404(Tag,slug=tag_slug)
				posts = Post.published.all()
				return posts.filter(tags__in=[tag])
		except KeyError:
				
			return Post.published.all()
	
	def get_context_data(self, **kwargs):
		context = super(PostListView, self).get_context_data(**kwargs)
		try:
			tag_slug = self.kwargs['tag_slug']
			context['tag'] = Tag.objects.get(slug=tag_slug)
			return context
		except KeyError:
			return context



def post_detail(request, year, month, day, post):
	post = get_object_or_404(Post, status='published',publish__year=year, publish__month=month, publish__day=day, slug=post)
	
	comments = post.comments.filter(active=True)

	if request.method == 'POST':
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			new_comment = comment_form.save(commit=False)
			new_comment.post = post
			new_comment.save()
	else:
		comment_form = CommentForm()
		new_comment = False
	post_tags_ids = post.tags.values_list('id',flat=True)
	similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
	similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
	return render(request,'blog/post/detail.html', {'post': post,'comments': comments,'comment_form': comment_form, 'new_comment': new_comment, 'similar_posts': similar_posts})

def post_share(request, post_id):
	post = get_object_or_404(Post, id=post_id, status='published')
	sent = False

	if request.method == 'POST':
		form = EmailPostForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = '{} ({}) zachęcam do przeczytania "{}"'.format(cd['name'], cd['email'], post.title)
			message = 'Przeczytaj post "{}" na stronie {} \n \n Komentarz dodany przez {}: {}'.format(post.title, post_url, cd['name'],cd['comments'])
			send_mail(subject, message, 'admin@myblog.com', [cd['to']],fail_silently=True)
			sent = True
	else:
		form = EmailPostForm()
	return render(request, 'blog/post/share.html',{'post': post,'form': form, 'sent':sent})

def post_search(request):
	form = SearchForm
	query = None
	results = []
	if 'query' in request.GET:
		form = SearchForm(request.GET)
		if form.is_valid():
			query = form.cleaned_data['query']
			results = Post.objects.annotate(search=SearchVector('title', 'body'),).filter(search=query)
	return render(request,'blog/post/search.html', {'form': form, 'query': query, 'results':results})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static "css/blog.css" %}">
</head>
<body>
	<div id="content">
		{% block content %}
		{% endblock %}
	</div>
	<div id="sidebar">
	<h2>Mój Blog</h2>
		<p>To jest mój blog. Dotychczas opublikowałem {% total_posts %} postów</p>
		<h4>Najnowsze posty</h4>
		{% show_latest_posts 5 %}
		<h4>Najczęściej komentowane posty</h4>
		{% get_most_commented_posts as most_commented_posts %}
		<ul>
			{% for post in most_commented_posts %}
			<li>
				<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
			</li>
			{% endfor %}
		</ul>	
	</div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">Opublikowany {{ post.publish }} przez {{ post.author }}</p>
{{ post.body|linebreaks }}
<p><a href="{% url "blog:post_share" post.id %}">Udostepnij post</a>  </p>

<h2>Podobne Posty</h2>
{% for post in similar_posts %}
<p> <a href="{{ post.get_absolute_url }}">{{ post.title }} </p>
{% empty %}
	Nie ma podobnych post.
{% endfor %}

{% with comments.count as total_comments %}
<h2>{{ total_comments }} komentarz{{ total_comments|pluralize:"y" }}</h2>
{% endwith %}

{% for comment in comments %}
 <div class="comment">
 	<p class="info">
 		Komentarz {{ forloop.counter }} dodany przez {{ comment.name }}
 		{{ comment.created }}
	</p>
	{{ comment.body|linebreaks }}
 </div>
 {% empty %}
 <p>Nie ma jeszcze żadnych komentarzy.</p>
{% endfor %}

 {% if new_comment %}
 	<h2>Twój komentarz został dodany.</h2>
 {% else %}
 	<h2>Dodaj nowy komentarz</h2>

	<form action="." method="post">
		{{ comment_form.as_p }}
		{% csrf_token %}
		<p><input type="submit" value="Dodaj komentarz" ></p>
	</form>
 {% endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
	{% for post in latest_posts %}
	 <li>
	 	<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
	</li>
	{% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}Mój blog{% endblock %}

{% block content %}
	<h1>Mój Blog</h1>
	{% if tag %}
		<h2>Posty oznaczone tagiem "{{ tag.name }}"</h2>
	{% endif %}
	{% for post in posts %}
		<h2>
			<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
			<p class="tags">Tagi: 
				{% for tag in post.tags.all %}
				<a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
				{% if not forloop.last %}, {% endif %}
				{% endfor %}
			</p>
		</h2>
		<p class="date">Opublikowany {{ post.publish }} przez {{ post.author }}</p>
		{{ post.body|truncatewords:30|linebreaks}}
	{% endfor %}
	{% include "pagination.html" with page=page_obj %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Udostępnij post{% endblock %}

{% block content %}
	{% if sent %}
	<h1>Wiadomość została wysłana</h1>
	<p>Wysłanie posta "{{ post.title }}" do {{ form.cleaned_data.to }} zakończyło się sukcesem</p>
	{% else %}
	<h1>Udostępnij "{{ post.title }}" przez e-mail</h1>
	<form action="." method="post">
		{{ form.as_p }}
		{% csrf_token %}
		<input type="submit" value="Wyślij wiadomość e-mail">
	</form>
	{% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous %}
		<a href="?page={{ page.previous_page_number }}">Poprzednia</a>
		{% endif %}
	<span class="current">
		Strona {{ page.number }} z {{ page.paginator.num_pages }}.
	</span>
	{% if page.has_next %}
		<a href="?page={{ page.next_page_number }}">Następna</a>
		{% endif %}
	</span>
</div>